#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "gruvbox"
colorscheme_bg = "dark"

# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true

# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"
statusline_iseparator = "bar"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = true 

#auto_completion_delay = 200
autocomplete_method = "deoplete"

filemanager = "nerdtree"

# project_rooter_outermost
project_rooter_outermost = false

# Enable/Disable show mode on statusline
enable_statusline_mode = true

# Set SpaceVim buffer index type
buffer_index_type = 4
# 0: 1 ➛ ➊
# 1: 1 ➛ ➀
# 2: 1 ➛ ⓵
# 3: 1 ➛ ¹
# 4: 1 ➛ 1
# left sections of statusline
statusline_left_sections = [
	'winnr',
	'major mode',
	'filename',
	'fileformat',
	'minor mode lighters',
	'version control info',
	'search status'
]

# right sections of statusline
statusline_right_sections = [
	'cursorpos',
	'percentage',
	'input method',
	'date',
	'time'
]

# statusline
[[layers]]
  name = "core#statusline"

# Enable autocomplete layer
[[layers]]
name = 'core'
filetree_show_hidden = true
enable_smooth_scrolling = true

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "smart"
auto_completion_enable_snippets_in_popup = true

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "denite"

[[layers]]
name = 'git'

# VersionControl
#Show a diff using Vim its sign column
#Show vcs info on statusline
[[layers]]
name = 'VersionControl'

# Fuzzy finder
[[layers]]
name = "unite"

#=======================================================
#      programimg lang
#=======================================================

# bash 
[[layers]]
name = "lang#sh"

# c++ 
[[layers]]
name = 'lang#c'
name = "format"
enable_clang_syntax_highlight = true

# code format
[[layers]]
name = "format"

# python3 
[[layers]]
name = "lang#python"

# assembly 
[[layers]]
name = "lang#assembly"

# This is an example for adding custom plugins lilydjwg/colorizer

#UI
[[layers]]
name = "ui"
   enable_sidebar = false
    enable_scrollbar = false
    enable_indentline = true
    enable_cursorword = false
    indentline_char = '|'
    conceallevel = 0
    concealcursor = ''
    cursorword_delay = 50
    cursorword_exclude_filetype = []
    indentline_exclude_filetyps = []


# spacevim lsp 
[[layers]]
name = "lsp"

filetypes = [
	"python"
]

#  hack
[[layers]]
name = "lang#hack"

